---
language: bash
# addons:
#   apt:
#     sources:
#     - debian-sid
#     packages:
#     - shellcheck
before_install:
  - sudo add-apt-repository ppa:duggan/bats --yes
  - sudo apt-get update -qq
  - sudo apt-get install -qq bats
  - sudo apt-get install -qq gnupg
  - sudo apt-get install -qq expect
script:
  # - make test
  - make bats
